---
- name: Create a user and group (devops), install apache
  hosts: week
  become: true
  tasks:
    - name: Create a group Devops
      group:
        name: devops
        state: present

    - name: Create a user
      user:
        name: Sairaj
        group: devops
        state: present
        create_home: yes
        shell: /bin/bash

    - name: Update cache
      apt:
        update_cache: yes

    - name: Install apache
      apt:
        name: apache2
        state: present

    - name: Create file
      copy:
        dest: /var/www/html/index.html
        content: "<html><head><title>Ansible week assignment</title></head><body><h1>My Ansible training wraps up here!</h1></body></html>"

    - name: Restart apache
      service:
        name: apache2
        state: restarted
        enabled: yes

